### ISSUE TITLE
Platform::WindowlessEglApplication::tryCreateContext(): cannot initialize EGL: EGL_NOT_INITIALIZED

### ISSUE THREAD

**Issue by yifan123** [facebookresearch/habitat-lab#654] opened 2021-06-07 17:46 UTC
## ❓ Questions and Help

Hi there,

I'm trying to set up habitat-sim on a remote CentOS Linux release 7.4.1708 (Core) machine and running into the following error when trying to run simulations. Any help with installation would be appreciated:

    I0607 19:03:14.663993 106203 SceneGraph.h:93] Created 
    DrawableGroup:Platform::WindowlessEglApplication::tryCreateContext(): cannot initialize EGL: EGL_NOT_INITIALIZED
    WindowlessContext: Unable to create windowless context

## Specs

CentOS Linux release 7.4.1708 (Core) with 8 NVIDIA GPUs on **slurm**.

## Steps to recreate

    conda create -n habitat python=3.7
    conda activate habitat

* Install habitat-sim

```
conda install -c aihabitat -c conda-forge habitat-sim headless
```

* Install Habitat-Lab

```
git clone --branch v0.1.7 git@github.com:facebookresearch/habitat-lab.git
cd habitat-lab
python -m pip install -r requirements.txt
python -m pip install -r habitat_baselines/rl/requirements.txt
python -m pip install -r habitat_baselines/rl/ddppo/requirements.txt
python setup.py develop --all
```

* Download the `test scenes data`and extract `data` folder in zip to `habitat-lab/data/`
* Run the example script `python examples/example.py`

and got the error

```
2021-06-07 21:10:03,080 Initializing dataset PointNav-v1
2021-06-07 21:10:03,611 initializing sim Sim-v0
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0607 21:10:03.612891 59483 ManagedContainerBase.cpp:19] ManagedContainerBase::convertFilenameToJSON : Filename : default changed to proposed JSON configuration filename : default.scene_dataset_config.json
I0607 21:10:03.613116 59483 AttributesManagerBase.h:283] AttributesManager<T>::createFromJsonOrDefaultInternal  (Dataset) : Proposing JSON name : default.scene_dataset_config.json from original name : defa$
lt | This file  does not exist.
I0607 21:10:03.613293 59483 AssetAttributesManager.cpp:117] Asset attributes (capsule3DSolid : capsule3DSolid_hemiRings_4_cylRings_1_segments_12_halfLen_0.75_useTexCoords_false_useTangents_false) created a$
d registered.
I0607 21:10:03.613397 59483 AssetAttributesManager.cpp:117] Asset attributes (capsule3DWireframe : capsule3DWireframe_hemiRings_8_cylRings_1_segments_16_halfLen_1) created and registered.
I0607 21:10:03.613468 59483 AssetAttributesManager.cpp:117] Asset attributes (coneSolid : coneSolid_segments_12_halfLen_1.25_rings_1_useTexCoords_false_useTangents_false_capEnd_true) created and registered$
I0607 21:10:03.613514 59483 AssetAttributesManager.cpp:117] Asset attributes (coneWireframe : coneWireframe_segments_32_halfLen_1.25) created and registered.
I0607 21:10:03.613569 59483 AssetAttributesManager.cpp:117] Asset attributes (cubeSolid : cubeSolid) created and registered.
I0607 21:10:03.613596 59483 AssetAttributesManager.cpp:117] Asset attributes (cubeWireframe : cubeWireframe) created and registered.
I0607 21:10:03.613658 59483 AssetAttributesManager.cpp:117] Asset attributes (cylinderSolid : cylinderSolid_rings_1_segments_12_halfLen_1_useTexCoords_false_useTangents_false_capEnds_true) created and regi$
tered.
I0607 21:10:03.613709 59483 AssetAttributesManager.cpp:117] Asset attributes (cylinderWireframe : cylinderWireframe_rings_1_segments_32_halfLen_1) created and registered.
I0607 21:10:03.613749 59483 AssetAttributesManager.cpp:117] Asset attributes (icosphereSolid : icosphereSolid_subdivs_1) created and registered.
I0607 21:10:03.613777 59483 AssetAttributesManager.cpp:117] Asset attributes (icosphereWireframe : icosphereWireframe_subdivs_1) created and registered.
I0607 21:10:03.613816 59483 AssetAttributesManager.cpp:117] Asset attributes (uvSphereSolid : uvSphereSolid_rings_8_segments_16_useTexCoords_false_useTangents_false) created and registered.
I0607 21:10:03.613853 59483 AssetAttributesManager.cpp:117] Asset attributes (uvSphereWireframe : uvSphereWireframe_rings_16_segments_32) created and registered.
I0607 21:10:03.613870 59483 AssetAttributesManager.cpp:105] AssetAttributesManager::buildCtorFuncPtrMaps : Built default primitive asset templates : 12
I0607 21:10:03.615538 59483 SceneDatasetAttributesManager.cpp:23] File (default) not found, so new default dataset attributes created and registered.
I0607 21:10:03.615561 59483 MetadataMediator.cpp:47] MetadataMediator::createDataset : Dataset default successfully created.
I0607 21:10:03.622299 59483 AttributesManagerBase.h:283] AttributesManager<T>::createFromJsonOrDefaultInternal  (Physics Manager) : Proposing JSON name : ./data/default.physics_config.json from original na$
e : ./data/default.physics_config.json | This file  does not exist.
I0607 21:10:03.622355 59483 PhysicsAttributesManager.cpp:27] File (./data/default.physics_config.json) not found, so new default physics manager attributes created and registered.
I0607 21:10:03.622366 59483 AbstractObjectAttributesManagerBase.h:175] AbstractObjectAttributesManager<T>::createObject  (Stage) : Making attributes with handle : data/scene_datasets/habitat-test-scenes/sk$
kloster-castle.glb
I0607 21:10:03.622376 59483 ManagedContainerBase.cpp:19] ManagedContainerBase::convertFilenameToJSON : Filename : data/scene_datasets/habitat-test-scenes/skokloster-castle.glb changed to proposed JSON conf$
guration filename : data/scene_datasets/habitat-test-scenes/skokloster-castle.stage_config.json
I0607 21:10:03.622828 59483 AttributesManagerBase.h:283] AttributesManager<T>::createFromJsonOrDefaultInternal  (Stage) : Proposing JSON name : data/scene_datasets/habitat-test-scenes/skokloster-castle.sta$
e_config.json from original name : data/scene_datasets/habitat-test-scenes/skokloster-castle.glb | This file  does not exist.
I0607 21:10:03.623425 59483 AbstractObjectAttributesManagerBase.h:181] AbstractObjectAttributesManager<T>::createObject  (Stage) : Done making attributes with handle : data/scene_datasets/habitat-test-scen$
s/skokloster-castle.glb
I0607 21:10:03.623435 59483 AbstractObjectAttributesManagerBase.h:188] File (data/scene_datasets/habitat-test-scenes/skokloster-castle.glb) exists but is not a recognized config filename extension, so new $
efault Stage attributes created and registered.
I0607 21:10:03.623456 59483 Simulator.cpp:156] Loading navmesh from data/scene_datasets/habitat-test-scenes/skokloster-castle.navmesh
I0607 21:10:03.624747 59483 Simulator.cpp:158] Loaded.
I0607 21:10:03.624779 59483 SceneGraph.h:93] Created DrawableGroup:
Platform::WindowlessEglApplication::tryCreateContext(): cannot initialize EGL: EGL_NOT_INITIALIZED
WindowlessContext: Unable to create windowless context
```

**Comment by erikwijmans** [comment] 2021-06-07 19:11
Duplicate of https://github.com/facebookresearch/habitat-sim/issues/1298

**Closed by erikwijmans** 2021-06-07 19:11 UTC
